apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-python-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-python-service
