steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-app:$SHORT_SHA']

  - name: 'gcr.io/k8s-skaffold/skaffold'
    args: ['run', '--filename=skaffold.yaml']

images:
  - 'asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 1064351983714-compute@developer.gserviceaccount.com
