substitutions:
  _RELEASE_ID: "rel-003"

steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: [
    'build',
    '--builder=gcr.io/buildpacks/builder',
    '--publish', 'asia-south1-docker.pkg.dev/onyx-antler-459216-j6/my-repo/app:$BUILD_ID'
  ]
  id: Build and package Python app

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "${_RELEASE_ID}",
      "--delivery-pipeline", "cloudrun-python-pipeline",
      "--region", "asia-south1",
      "--images", "app=asia-south1-docker.pkg.dev/onyx-antler-459216-j6/my-repo/app:$BUILD_ID"
    ]

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 880653953247-compute@developer.gserviceaccount.com
