steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    [
      'build',
      '--builder=gcr.io/buildpacks/builder',
      '--publish',
      'asia-south1-docker.pkg.dev/onyx-antler-459216-j6/my-repo/app:rel-20240508-1800'
    ]
  id: Build and package app

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'gcloud'
  args:
    [
      'deploy', 'releases', 'create', 'rel-20240508-1800',
      '--delivery-pipeline', 'cloudrun-python-pipeline',
      '--region', 'asia-south1',
      '--images', 'app=asia-south1-docker.pkg.dev/onyx-antler-459216-j6/my-repo/app:rel-20240508-1800'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 880653953247-compute@developer.gserviceaccount.com
