steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'build', '-t', 'asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-python-service', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [ 'push', 'asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-python-service' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        skaffold render \
          --file=skaffold.yaml \
          --default-repo=asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo \
          --digest-source=tag \
          --output=rendered.yaml

images:
  - asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-python-service

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 1064351983714-compute@developer.gserviceaccount.com
