apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-python-pipeline
description: Application pipeline for Cloud Run
serialPipeline:
  stages:
  - targetId: dev-env
    profiles: [dev]
  - targetId: qa-env
    profiles: [qa]
  - targetId: prod-env
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-env
description: Cloud Run development environment
run:
  location: projects/enhub-cloud-interns/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa-env
description: Cloud Run QA environment
run:
  location: projects/enhub-cloud-interns/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-env
description: Cloud Run production environment
run:
  location: projects/enhub-cloud-interns/locations/asia-south1
