apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-python-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: REPLACE_IMAGE
          ports:
            - containerPort: 8080
