steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'asia-south1-docker.pkg.dev/enhub-cloud-interns/my-app/hello-python'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia-south1-docker.pkg.dev/enhub-cloud-interns/my-app/hello-python'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        skaffold render --digest-source=tag --output=rendered.yaml --filename=skaffold.yaml
        skaffold apply --filename=skaffold.yaml

images:
  - asia-south1-docker.pkg.dev/enhub-cloud-interns/my-app/hello-python

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 1064351983714-compute@developer.gserviceaccount.com
