apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-python-pipeline
description: Deploys a simple Python app to Cloud Run
serialPipeline:
  stages:
    - targetId: dev
      profiles: []

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment for Cloud Run
run:
  location: asia-south1
  service: my-app  # ✅ must match Skaffold's serviceName
