apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-dev
spec:
  template:
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/onyx-antler-459216-j6/my-repo/app
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
