apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: my-python-service
manifests:
  rawYaml:
    - cloudrun-service.yaml
deploy:
  cloudrun:
    location: asia-south1
    projectId: enhub-cloud-interns
    service: my-python-service
