apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: hello-python
build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/enhub-cloud-interns/my-app/hello-python
  tagPolicy:
    gitCommit: {}
  googleCloudBuild:
    projectId: enhub-cloud-interns
deploy:
  cloudrun:
    region: asia-south1
    projectId: enhub-cloud-interns
    service: hello-python
profiles:
  - name: clouddeploy
    deploy:
      cloudrun:
        region: asia-south1
        projectId: enhub-cloud-interns
        service: hello-python
