apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: cloudrun-deploy
build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-app

deploy:
  googleCloudDeploy:
    deliveryPipeline: cloudrun-python-pipeline
    target: dev
    region: asia-south1
    render:
      include:
        - run
