apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: hello-python
build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/enhub-cloud-interns/my-app/hello-python
  googleCloudBuild:
    projectId: enhub-cloud-interns

manifests:
  rawYaml:
    - cloudrun-service.yaml

deploy:
  cloudrun: {}
