apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: cloudrun-deploy
build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/enhub-cloud-interns/my-repo/my-app

deploy:
  cloudrun:
    region: asia-south1
    project: enhub-cloud-interns
    services:
      - name: my-app
